version: "3"
services:
  user-service:
    image: services/user-service
    build:
      context: ${BACKEND_REPO_ABSOLUTE_PATH}/user-service/
      dockerfile: ${INFRA_REPO_ABSOLUTE_PATH}/images/user-service.Dockerfile
    networks:
      - user-service-network
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - user-service-db
  
  user-service-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: user-service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - user-service-network
    volumes:
      - user_service_db_data:/var/lib/db
    ports:
      - "5432:5432"

networks:
  user-service-network:

volumes:
  user_service_db_data:
