apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-service
  namespace: banka-3-dev
  labels:
    service: bank-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: bank-service
  template:
    metadata:
      labels:
        service: bank-service
    spec:
      containers:
      - image: harbor.k8s.elab.rs/banka-3/bank-service:latest
        imagePullPolicy: Always
        name: bank-service
        env:
          - name: spring.datasource.url
            value: jdbc:postgresql://banka-3-ha:5432/main_database?currentSchema=bank_service_schema
          - name: spring.datasource.username
            valueFrom:
              secretKeyRef:
                name: banka-3-pguser-admin
                key: user
          - name: spring.datasource.password
            valueFrom:
              secretKeyRef:
                name: banka-3-pguser-admin
                key: password
          - name: spring.jpa.hibernate.ddl-auto
            value: update
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 2
            memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: bank-service
  namespace: banka-3-dev
  labels:
    service: bank-service
spec:
  type: ClusterIP
  selector:
    service: bank-service
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082